from Cheque import Cheque
from Gramatica import Gramatica

def app(valor):
    cheque = Cheque()
    corretor = Gramatica()
    
    saida = cheque.extenso(valor)
    saida = corretor.corrigir(saida)
    
    print(saida)    
 
    return saida

assert app("1.00") == "um real"
assert app("2.00") == "dois reais"
assert app("18.00") == "dezoito reais"
assert app("10.00") == "dez reais"
assert app("11.00") == "onze reais"
assert app("21.00") == "vinte e um reais"
assert app("53.00") == "cinquenta e três reais"
assert app("77.00") == "setenta e sete reais"
assert app("100.00") == "cem reais"
assert app("125.00") == "cento e vinte e cinco reais"
assert app("258.00") == "duzentos e cinquenta e oito reais"
assert app("316.00") == "trezentos e dezesseis reais"
assert app("525.00") == "quinhentos e vinte e cinco reais"
assert app("689.00") == "seiscentos e oitenta e nove reais"
assert app("763.00") == "setecentos e sessenta e três reais"
assert app("842.00") == "oitocentos e quarenta e dois reais"
assert app("967.00") == "novecentos e sessenta e sete reais"
assert app("1000.00") == "mil reais"
assert app("1008.00") == "mil e oito reais"
assert app("1015.00") == "mil e quinze reais"
assert app("1211.00") == "mil duzentos e onze reais"
assert app("1371.00") == "mil trezentos e setenta e um reais"
assert app("1489.00") == "mil quatrocentos e oitenta e nove reais"
assert app("1598.00") == "mil quinhentos e noventa e oito reais"
assert app("1632.00") == "mil seiscentos e trinta e dois reais"
assert app("1745.00") == "mil setecentos e quarenta e cinco reais"
assert app("1887.00") == "mil oitocentos e oitenta e sete reais"
assert app("1993.00") == "mil novecentos e noventa e três reais"
assert app("2013.00") == "dois mil e treze reais"
assert app("2453.00") == "dois mil quatrocentos e cinquenta e três reais"
assert app("3004.00") == "três mil e quatro reais"
assert app("4204.00") == "quatro mil duzentos e quatro reais"
assert app("5011.00") == "cinco mil e onze reais"
assert app("10258.00") == "dez mil duzentos e cinquenta e oito reais"
assert app("12526.00") == "doze mil quinhentos e vinte e seis reais"
assert app("100000.00") == "cem mil reais"
assert app("896478.00") == "oitocentos e noventa e seis mil quatrocentos e setenta e oito reais"
assert app("1000000.00") == "um milhão de reais"
assert app("1125697.00") == "um milhão cento e vinte e cinco mil seiscentos e noventa e sete reais"
assert app("2156987.00") == "dois milhões cento e cinquenta e seis mil novecentos e oitenta e sete reais"
assert app("8541297.00") == "oito milhões quinhentos e quarenta e um mil duzentos e noventa e sete reais"
assert app("100000000.00") == "cem milhões de reais"
assert app("259874213.00") == "duzentos e cinquenta e nove milhões oitocentos e setenta e quatro mil duzentos e treze reais"
assert app("300000001.00") == "trezentos milhões e um reais"
assert app("400000015.00") == "quatrocentos milhões e quinze reais"
assert app("400000015.00") == "quatrocentos milhões e quinze reais"
assert app("1000000000.00") == "um bilhão de reais"
assert app("2555675645.00") == "dois bilhões quinhentos e cinquenta e cinco milhões seiscentos e setenta e cinco mil seiscentos e quarenta e cinco reais"
assert app("8552458754.00") == "oito bilhões quinhentos e cinquenta e dois milhões quatrocentos e cinquenta e oito mil setecentos e cinquenta e quatro reais"
assert app("10000000000.00") == "dez bilhões de reais"
assert app("12000000000.00") == "doze bilhões de reais"
assert app("86896896895.00") == "oitenta e seis bilhões oitocentos e noventa e seis milhões oitocentos e noventa e seis mil oitocentos e noventa e cinco reais"
assert app("100000000000.00") == "cem bilhões de reais"
assert app("120000000000.00") == "cento e vinte bilhões de reais"
assert app("965467468766.00") == "novecentos e sessenta e cinco bilhões quatrocentos e sessenta e sete milhões quatrocentos e sessenta e oito mil setecentos e sessenta e seis reais"
assert app("999999999999.00") == "novecentos e noventa e nove bilhões novecentos e noventa e nove milhões novecentos e noventa e nove mil novecentos e noventa e nove reais"

assert app("10.25") == "dez reais e vinte e cinco centavos"
assert app("11.10") == "onze reais e dez centavos"
assert app("21.75") == "vinte e um reais e setenta e cinco centavos"
assert app("53.52") == "cinquenta e três reais e cinquenta e dois centavos"
assert app("77.89") == "setenta e sete reais e oitenta e nove centavos"
assert app("100.23") == "cem reais e vinte e três centavos"
assert app("125.58") == "cento e vinte e cinco reais e cinquenta e oito centavos"
assert app("245.96") == "duzentos e quarenta e cinco reais e noventa e seis centavos"
assert app("525.78") == "quinhentos e vinte e cinco reais e setenta e oito centavos"
assert app("689.36") == "seiscentos e oitenta e nove reais e trinta e seis centavos"
assert app("763.15") == "setecentos e sessenta e três reais e quinze centavos"
assert app("842.19") == "oitocentos e quarenta e dois reais e dezenove centavos"
assert app("967.17") == "novecentos e sessenta e sete reais e dezessete centavos"
assert app("8552458754.94") == "oito bilhões quinhentos e cinquenta e dois milhões quatrocentos e cinquenta e oito mil setecentos e cinquenta e quatro reais e noventa e quatro centavos"
